# Generated by Django 5.1.7 on 2025-03-08 23:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Portfolio Index Page',
                'verbose_name_plural': 'Portfolio Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Tag value', max_length=255)),
                ('category', models.CharField(choices=[('year', 'Year'), ('framework', 'Framework'), ('programming_language', 'Programming Language'), ('topic', 'Topic'), ('subtopic', 'Subtopic'), ('default', 'Default')], default='default', help_text='Category of the tag', max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'unique_together': {('value', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('main_button_text', models.CharField(help_text='Text for the main call-to-action button', max_length=50)),
                ('secondary_button_text', models.CharField(blank=True, help_text='Text for the secondary button (optional)', max_length=50)),
                ('secondary_button_url', models.URLField(blank=True, help_text='URL for the secondary button')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tags', models.ManyToManyField(blank=True, related_name='portfolio_items', to='portfolio.tag')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
            },
            bases=('wagtailcore.page',),
        ),
    ]
