# Generated by Django 5.1.6 on 2025-03-04 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20250304_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioindexpage',
            options={'verbose_name': 'Portfolio Index Page', 'verbose_name_plural': 'Portfolio Index Pages'},
        ),
    ]
