# Generated by Django 5.1.6 on 2025-03-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioindexpage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PortfolioItemTag',
        ),
    ]
