name: CMS Check and Deploy Simulation

on:
  workflow_call:
    secrets:
      LINUX_SSH_PRIVATE_KEY:
        required: true
      LINUX_USER_DEVOPS:
        required: true
      LINUX_SERVER_IP:
        required: true
    outputs:
      had_changes:
        description: "Whether changes were detected"
        value: ${{ jobs.cms-deploy.outputs.changes_detected }}
      action_taken:
        description: "Action taken during deployment"
        value: ${{ jobs.cms-deploy.outputs.action }}

jobs:
  cms-deploy:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check-changes.outputs.changes }}
      action: ${{ steps.deploy--cms.outputs.action_taken }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check CMS Directory Changes
        id: check-changes
        run: |
          echo "Checking for code changes in CMS directory..."
          
          # Check if there are changes in the latest commit
          CHANGES=$(git diff-tree --no-commit-id --name-only -r HEAD -- ./wagtail_cms_portfolio2025)
          
          if [ -z "$CHANGES" ]; then
            echo "No changes detected in wagtail_cms_portfolio2025 directory"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in wagtail_cms_portfolio2025 directory:"
            echo "$CHANGES"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Build & Publish image
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          echo "Building updated Wagtail CMS Docker image..."
          echo "BUILT=true" >> $GITHUB_ENV

          echo "Publishing updated Wagtail CMS Docker image..."
          echo "PUSHED=true" >> $GITHUB_ENV

      - name: Ssh in and Deploy Updated CMS image
        id: deploy--cms
        env:
          SSH_KEY: ${{ secrets.LINUX_SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.LINUX_USER_DEVOPS }}
          SERVER_IP: ${{ secrets.LINUX_SERVER_IP }}
          DEPLOY_POSTGRES_NEEDED: true
        run: |
          # Debug environment variables
          echo "Debug - Checking if variables are set:"
          echo "SSH_USER is set: $(if [ -n "$SSH_USER" ]; then echo "YES"; else echo "NO"; fi)"
          echo "SERVER_IP is set: $(if [ -n "$SERVER_IP" ]; then echo "YES"; else echo "NO"; fi)"

          # Setup SSH
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SERVER_IP
            User $SSH_USER
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          END

          ssh prod << EOF
          set -e

          cd ~

          #####
          echo "Just a little check to make sure runner has sshed into the server"
          # Get hostname - shows the server's configured name
          echo "Remote hostname:"
          hostname

          # Check running processes - shows what's running on the server
          # didnt work:
          # echo "Remote running Docker containers:"
          # "docker ps"
          echo "Docker path: "
          which docker
          /usr/bin/docker ps -a

          # Check server uptime - shows how long the server has been running
          echo "Remote server uptime:"
          uptime

          #### EXPERIMENT
          # Force a login shell environment
          export PATH=/usr/bin:/bin:/usr/local/bin:/sbin:/usr/sbin:\$PATH
          # Print current PATH for debugging
          echo "Current PATH: " ${PATH}
          # Try to locate the commands
          which free
          which df
          # Run the commands with full paths
          echo "Remote system resources:"
          /usr/bin/free -h && /bin/df -h
          EOF
          #########################
          ## For deployment, dont forget to connect the container to network main-network--npm020325
          #########################
          if [[ "${{ steps.check-changes.outputs.changes }}" == "true" ]]; then
            echo "Deploying new CMS version..."
            echo "action_taken=New version deployed" >> $GITHUB_OUTPUT
          else
            echo "No changes detected, skipping deployment"
            echo "action_taken=No deployment needed" >> $GITHUB_OUTPUT
          fi

      - name: Status Report
        run: |
          echo "CMS Deployment Status:"
          echo "Changes Detected: ${{ steps.check-changes.outputs.changes }}"
          echo "Action Taken: ${{ steps.deploy--cms.outputs.action_taken }}"
