name: Frontend Check and Deploy Simulation

on:
  workflow_call:
    secrets:
      LINUX_SSH_PRIVATE_KEY:
        required: true
      LINUX_USER_DEVOPS:
        required: true
      LINUX_SERVER_IP:
        required: true
      GHPAT_021425_CICD_GHCR_REPO_WORKFLOW_WRDPACKAGES:
        required: true
    outputs:
      had_changes:
        description: "Whether changes were detected"
        value: ${{ jobs.fe-deploy.outputs.changes_detected }}
      action_taken:
        description: "Action taken during deployment"
        value: ${{ jobs.fe-deploy.outputs.action }}

jobs:
  fe-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # Needed for artifact operations
    outputs:
      changes_detected: ${{ steps.check-changes.outputs.changes }}
      action: ${{ steps.deploy.outputs.action_taken }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for better change detection

      # Setup GitHub CLI for artifact operations
      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI authentication..."
          echo ${{ github.token }} | gh auth login --with-token

      # Download last successful deployment marker if it exists
      - name: Download last successful deployment marker
        id: download-marker
        continue-on-error: true  # Continue if no marker exists yet
        run: |
          mkdir -p ./deployment-markers
          
          # Try to download the artifact using the GitHub CLI
          echo "Attempting to download latest fe-last-deployed-commit artifact..."
          gh artifact download fe-last-deployed-commit --dir ./deployment-markers --repo ${{ github.repository }} || true
          
          # Check if the download was successful
          if [ -f "./deployment-markers/last-fe-commit.txt" ]; then
            echo "✅ Successfully downloaded previous deployment marker"
          else
            echo "⚠️ No previous deployment marker found or download failed"
          fi

      # Determine last deployed commit hash
      - name: Get last deployed commit hash
        id: get-last-commit
        run: |
          if [ -f "./deployment-markers/last-fe-commit.txt" ]; then
            LAST_COMMIT=$(cat ./deployment-markers/last-fe-commit.txt)
            echo "Last successfully deployed frontend commit: $LAST_COMMIT"
            echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT
          else
            # If no marker exists, get a commit far back enough to capture all changes
            # This will trigger a build on first run
            LAST_COMMIT=$(git rev-list --max-parents=0 HEAD)
            echo "No previous deployment marker found. Using initial commit: $LAST_COMMIT"
            echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT
          fi

      - name: Check NextJS Directory Changes
        id: check-changes
        run: |
          echo "Checking for code changes in NextJS directory since last deployment..."
          
          # Debug: Show the commit we're comparing against
          echo "Comparing current commit with: ${{ steps.get-last-commit.outputs.last_commit }}"
          
          # Check for changes between last deployed commit and current HEAD
          CHANGES=$(git diff --name-only ${{ steps.get-last-commit.outputs.last_commit }} HEAD -- ./nextjs_portfolio2025)
          
          if [ -z "$CHANGES" ]; then
            echo "No changes detected in nextjs_portfolio2025 directory since last deployment"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in nextjs_portfolio2025 directory since last deployment:"
            echo "$CHANGES"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Install YQ
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Load Environment Defaults
        id: env-defaults
        run: |
          # Extract NextJS environment variables from defaults file
          NEXTJS_DEFAULTS=$(yq e '.nextjs_defaults' .github/defaults/env-defaults.yml)
          echo "$NEXTJS_DEFAULTS" > ./nextjs_portfolio2025/prod.env

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHPAT_021425_CICD_GHCR_REPO_WORKFLOW_WRDPACKAGES }}
      
      - name: Build & Publish Image
        id: build-publish
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          echo "Building and publishing frontend Docker image..."
          
          # Build the NextJS Docker image with env file
          docker build \
            --build-arg NODE_ENV=production \
            --build-arg ENV_FILE=prod.env \
            -t ghcr.io/pmeaney/nextjs-prod-wnp-portfolio-2025:latest \
            ./nextjs_portfolio2025
          
          # Push the Docker image to GitHub Container Registry
          docker push ghcr.io/pmeaney/nextjs-prod-wnp-portfolio-2025:latest
          
          # Clean up
          rm ./nextjs_portfolio2025/prod.env
          
          echo "BUILT=true" >> $GITHUB_ENV
          echo "PUSHED=true" >> $GITHUB_ENV
          echo "build_status=success" >> $GITHUB_OUTPUT

      - name: Deploy
        id: deploy
        env:
          SSH_KEY: ${{ secrets.LINUX_SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.LINUX_USER_DEVOPS }}
          SERVER_IP: ${{ secrets.LINUX_SERVER_IP }}
          GHPAT: ${{ secrets.GHPAT_021425_CICD_GHCR_REPO_WORKFLOW_WRDPACKAGES }}
        run: |
          if [[ "${{ steps.check-changes.outputs.changes }}" == "true" ]]; then
            # Setup SSH - simplified approach
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            
            # Create SSH config with direct variable expansion
            cat >>~/.ssh/config <<EOF
            Host prod
              HostName $SERVER_IP
              User $SSH_USER
              IdentityFile ~/.ssh/id_ed25519
              StrictHostKeyChecking no
            EOF
            
            # Verify connection to server with simple commands
            echo "Verifying server connection..."
            ssh prod "hostname && which docker && uptime"
            
            # First authenticate with GHCR on the remote server
            echo "Authenticating with GitHub Container Registry on remote server..."
            ssh prod "echo '$GHPAT' | docker login ghcr.io -u ${{ github.actor }} --password-stdin"
            
            # Deploy to remote server
            ssh prod "docker pull ghcr.io/pmeaney/nextjs-prod-wnp-portfolio-2025:latest && \
                      docker rm -f nextjs-prod-wnp-portfolio-2025 || true && \
                      docker run -d \
                        --name nextjs-prod-wnp-portfolio-2025 \
                        --network main-network--npm020325 \
                        -p 3000:3000 \
                        ghcr.io/pmeaney/nextjs-prod-wnp-portfolio-2025:latest"
            
            echo "Deploying new frontend version..."
            echo "action_taken=New version deployed" >> $GITHUB_OUTPUT
            echo "deploy_status=success" >> $GITHUB_ENV
          else
            echo "No changes detected, skipping deployment"
            echo "action_taken=No deployment needed" >> $GITHUB_OUTPUT
          fi

      # Save deployment marker if deploy was successful
      - name: Save deployment marker
        if: steps.check-changes.outputs.changes == 'true' && env.deploy_status == 'success'
        run: |
          mkdir -p ./deployment-markers
          git rev-parse HEAD > ./deployment-markers/last-fe-commit.txt
          echo "Saved current commit as last deployed commit marker"

      # Upload the marker as an artifact
      - name: Upload deployment marker
        if: steps.check-changes.outputs.changes == 'true' && env.deploy_status == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: fe-last-deployed-commit
          path: ./deployment-markers/last-fe-commit.txt
          retention-days: 90

      - name: Status Report
        run: |
          echo "Frontend Deployment Status:"
          echo "Changes Detected: ${{ steps.check-changes.outputs.changes }}"
          echo "Action Taken: ${{ steps.deploy.outputs.action_taken }}"